using System;using System.Drawing;using System.IO;using System.Threading;using System.Windows.Forms;using System.Collections.Generic;using System.Diagnostics;
namespace MuMuBeans {static class ClockScreenTest {
sealed class Fixture:Form{public Bitmap Image;public Fixture(){FormBorderStyle=FormBorderStyle.None;StartPosition=FormStartPosition.Manual;Location=new Point(0,0);TopMost=true;DoubleBuffered=true;}protected override void OnPaint(PaintEventArgs e){e.Graphics.DrawImage(Image,ClientRectangle);}}
static bool Wait(Func<bool> condition,int ms){Stopwatch t=Stopwatch.StartNew();while(t.ElapsedMilliseconds<ms){Application.DoEvents();if(condition())return true;Thread.Sleep(5);}return false;}
public static void ClockOnly(string[] args){try{using(Bitmap b=new Bitmap(args[1]))using(Fixture form=new Fixture())using(GameClockWorker worker=new GameClockWorker()){form.ClientSize=new Size(b.Width/2,b.Height/2);form.Location=new Point(50,500);form.Image=b;form.Show();form.Refresh();Application.DoEvents();Native.SetForegroundWindow(form.Handle);worker.Configure(form.Handle);bool pass=Wait(()=>worker.RecoveryAt(Stopwatch.GetTimestamp()).Contains(args[2]),3000);Rectangle client=Native.ClientBounds(form.Handle),area=ClockReader.Area(client.Size);area.Offset(client.Location);string debug=" client="+client+" uncovered="+Native.Uncovered(form.Handle,area);if(Native.Uncovered(form.Handle,area))using(Bitmap actual=Native.Capture(area)){actual.Save(args[3]+".png");using(ClockReader reader=new ClockReader())debug+=" raw="+reader.Read(actual);}File.WriteAllText(args[3],(pass?"PASS ":"FAIL ")+worker.RecoveryAt(Stopwatch.GetTimestamp())+debug);Environment.ExitCode=pass?0:1;form.Hide();}}catch(Exception e){File.WriteAllText(args[3],e.ToString());Environment.ExitCode=1;}}
public static void Run(string[] args){List<string> rows=new List<string>();int failed=0;try{using(Bitmap original=new Bitmap(args[1]))using(Bitmap two=(Bitmap)original.Clone())using(Fixture form=new Fixture())using(Engine engine=new Engine()){
using(Graphics g=Graphics.FromImage(two))g.DrawImage(original,new Rectangle(1607,98,30,38),new Rectangle(1576,98,30,38),GraphicsUnit.Pixel);
form.ClientSize=original.Size;form.Image=original;form.Show();form.Refresh();Application.DoEvents();engine.Configure(form.Handle,new RectangleF(1576f/original.Width,98f/original.Height,122f/original.Width,38f/original.Height),150,true);
if(!Wait(()=>engine.GetSnapshot().Count==3,3000))throw new Exception("baseline failed");Wait(()=>false,1200);
form.Image=two;form.Refresh();if(!Wait(()=>engine.GetSnapshot().Triggers==1,1500))throw new Exception("drop failed");Snapshot s=engine.GetSnapshot();rows.Add("TARGET "+s.Recovery);if(s.Recovery!="恢复点：22 秒（游戏）")throw new Exception("37 - 15 target not frozen correctly");rows.Add("PASS 实际截图 OCR 37 → 少豆 → 固定恢复点22");double remaining=s.Remaining;string target=s.Recovery;
using(Bitmap black=new Bitmap(original.Width,original.Height)){form.Image=black;form.Refresh();Wait(()=>false,1100);s=engine.GetSnapshot();if(s.Recovery!=target||s.Triggers!=1||s.Remaining<=0||s.Remaining>=remaining)throw new Exception("blackout changed countdown/target");rows.Add("PASS 黑屏1.1秒：倒计时连续减少，恢复点不改变");form.Image=two;form.Refresh();Wait(()=>engine.GetSnapshot().Count==2,2500);s=engine.GetSnapshot();if(s.Recovery!=target||s.Triggers!=1)throw new Exception("return reset");rows.Add("PASS 恢复画面后：不重启计时、不改变固定恢复点");}form.Hide();}}
catch(Exception ex){failed++;rows.Add(ex.ToString());}File.WriteAllLines(args[2],rows);Environment.ExitCode=failed==0?0:1;}
}}


