using System;using System.Drawing;using System.IO;using System.Diagnostics;using System.Threading;using System.Windows.Forms;
namespace MuMuBeans {static class Clock55Live {
 sealed class Fixture:Form {public Bitmap Image;public Fixture(){FormBorderStyle=FormBorderStyle.None;TopMost=true;StartPosition=FormStartPosition.Manual;Location=new Point(20,50);DoubleBuffered=true;}protected override void OnPaint(PaintEventArgs e){e.Graphics.DrawImage(Image,ClientRectangle);}}
 static bool Wait(Func<bool> ok){Stopwatch s=Stopwatch.StartNew();while(s.ElapsedMilliseconds<3000){Application.DoEvents();if(ok())return true;Thread.Sleep(10);}return false;}
 public static void Run(string[] a){Directory.CreateDirectory(a[2]);string config=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"clock-region.txt"),old=File.Exists(config)?File.ReadAllText(config):null;var rows=new System.Collections.Generic.List<string>();try{
 using(Bitmap image=new Bitmap(a[1]))using(Bitmap shifted=new Bitmap(image.Width,image.Height+300))using(Bitmap black=new Bitmap(image.Width,image.Height))using(Fixture f=new Fixture())using(GameClockWorker w=new GameClockWorker()){
 using(Graphics g=Graphics.FromImage(shifted)){g.Clear(Color.Black);g.DrawImageUnscaled(image,0,300);}f.Image=image;f.ClientSize=new Size(image.Width/2,image.Height/2);f.Show();f.Refresh();Application.DoEvents();w.SetRegion(new RectangleF(.4f,.055f,.2f,.16f));w.Configure(f.Handle);
 if(!Wait(()=>w.State().Value==49&&w.State().Age<.6))throw new Exception("初始49未确认："+w.State().Status);rows.Add("PASS 实际测试窗口49连续确认，恢复点34");
 f.Image=black;f.Refresh();if(!Wait(()=>!w.State().Raw.HasValue&&w.State().Age>.65))throw new Exception("黑屏未过期");w.Export(a[2]);if(Directory.GetFiles(Path.Combine(a[2],"游戏时间"),"*.png").Length==0)throw new Exception("无失败图缓存");if(!w.RecoveryAt(Stopwatch.GetTimestamp()).Contains("未确认"))throw new Exception("使用了过期读数");rows.Add("PASS 黑屏拒绝过期读数，保存实际失败区域图片和原因");
 f.Image=shifted;f.ClientSize=new Size(shifted.Width/2,shifted.Height/2);f.Refresh();w.SetRegion(new RectangleF(835f/shifted.Width,360f/shifted.Height,200f/shifted.Width,140f/shifted.Height));if(!Wait(()=>w.State().Value==49&&w.State().Age<.6))throw new Exception("校准后未确认："+w.State().Status);rows.Add("PASS 改变窗口内容偏移后，手动区域恢复实际读取49");using(GameClockWorker loaded=new GameClockWorker()){if(Math.Abs(loaded.State().Region.Y-360f/shifted.Height)>.00001)throw new Exception("校准未保存");}rows.Add("PASS 区域设置保存并重新加载");f.Hide();}
 }catch(Exception e){rows.Add("FAIL "+e);Environment.ExitCode=1;}finally{if(old==null){if(File.Exists(config))File.Delete(config);}else File.WriteAllText(config,old);}File.WriteAllLines(Path.Combine(a[2],"实际校准与诊断验证.txt"),rows);}
}}
