using System;using System.Drawing;using System.Diagnostics;using System.Globalization;using System.IO;using System.Collections.Generic;
namespace MuMuBeans {
static class Clock57Bench {
 [STAThread] static void Main(string[] a){Run(a);}
 public static void Run(string[] a){if(a[0]=="--tracker"){Tracker(a[1]);return;}int correct=0,failed=0;var rows=new List<string>();using(ClockReader r=new ClockReader())foreach(string line in File.ReadAllLines(Path.Combine(a[0],"cases.tsv"))){string[] p=line.Split('\t');using(Bitmap b=new Bitmap(Path.Combine(a[0],p[0]))){Stopwatch sw=Stopwatch.StartNew();double? v=r.Read(b);bool pass=p[1]=="null"?!v.HasValue:v.HasValue&&Math.Abs(v.Value-double.Parse(p[1],CultureInfo.InvariantCulture))<.001;rows.Add((pass?"PASS":"FAIL")+"\t"+p[0]+"\texpected="+p[1]+"\tgot="+v+"\tms="+sw.Elapsed.TotalMilliseconds.ToString("F1",CultureInfo.InvariantCulture)+"\t"+r.LastReason);if(pass)correct++;else failed++;}}
 rows.Add("CORRECT="+correct+" FAILURES="+failed+" (saved local crops and artificial transforms; not independent match accuracy)");File.WriteAllLines(a[1],rows);Console.WriteLine(rows[rows.Count-1]);Environment.ExitCode=failed==0?0:1;}
 static void Tracker(string path){var rows=new List<string>();int failures=0;Action<bool,string> check=delegate(bool ok,string title){rows.Add((ok?"PASS ":"FAIL ")+title);if(!ok)failures++;};var t=new ClockTracker();check(!t.Observe(49,0)&&t.Observe(49,.05),"基准需两帧");check(!t.Observe(48,.10)&&t.Value==49&&t.Observe(49,.15)&&t.Value==49,"单帧错读少一秒后恢复，不污染确认值");check(!t.Observe(48,.20)&&t.Observe(48,.25)&&t.Value==48,"真实整数减一秒在第二帧确认");check(!t.Observe(18,.30)&&!t.Observe(18,.35)&&t.Value==48,"大跳变前两帧保持旧值");check(t.Observe(18,.40)&&t.Value==18,"持续大跳变第三帧重新确认");check(!t.Observe(null,.45)&&t.Value==18&&t.Stamp==.40,"空帧保留历史但不刷新时效");check(t.Observe(18,.50)&&t.Value==18,"游戏暂停不扣现实时间");check(!t.Observe(60,.55)&&!t.Observe(60,.60)&&t.Observe(60,.65),"新回合需三帧确认");t.Reset();check(!t.Observe(10,0)&&t.Observe(10,.05)&&!t.Observe(9.99,.10)&&t.Observe(9.94,.15)&&t.Value==9.94,"整数到小数连续下降两帧确认");check(!t.Observe(9.5,.20)&&t.Value==9.94&&t.Observe(9.94,.25)&&t.Value==9.94,"单帧小数跳变被阻止");check(!t.Observe(6.43,2)&&t.Observe(6.38,2.05)&&t.Value==6.38,"失去时间后重获需两帧，不推算未读秒数");check(GameClockWorker.Recovery(49).Contains("34")&&GameClockWorker.LateRecovery(40,6).Contains("34")&&GameClockWorker.Recovery(null).Contains("未确认"),"恢复点计算及未知时间不猜60");rows.Add("FAILURES="+failures);File.WriteAllLines(path,rows);Environment.ExitCode=failures==0?0:1;Console.WriteLine(rows[rows.Count-1]);}
}
}
