using System;using System.Collections.Generic;using System.Drawing;using System.IO;using System.Windows.Forms;
namespace MuMuBeans {static class Clock55Tests {
 public static void Run(string[] a){Directory.CreateDirectory(a[1]);var rows=new List<string>();int failures=0;Action<bool,string> check=delegate(bool ok,string s){rows.Add((ok?"PASS ":"FAIL ")+s);if(!ok)failures++;};try{
 var t=new ClockTracker();check(!t.Observe(49,0)&&t.Observe(49,.05)&&t.Value==49,"两帧建立基准");check(!t.Observe(48,.10)&&t.Value==49&&t.Observe(48,.15)&&t.Value==48,"整数边界两帧确认，单帧错一秒不立即替换");check(!t.Observe(30,.20)&&t.Value==48,"单帧大跳变不替换确认值");check(t.Observe(48,.25),"异常后正常恢复");check(!t.Observe(null,.30)&&t.Value==48,"遮挡保留已确认值但不更新时间戳");check(t.Observe(48,.35)&&t.Value==48,"游戏暂停保持相同时间，不按现实时间扣秒");check(!t.Observe(60,.40)&&!t.Observe(60,.45)&&t.Observe(60,.50),"跳到新回合60需三帧确认");check(!t.Observe(99,.55)&&t.Value==60,"越界数字拒绝");
 t.Reset();check(!t.Observe(10,0)&&t.Observe(10,.05)&&!t.Observe(9.99,.10)&&t.Observe(9.94,.15),"整数到小数两帧连续确认");check(!t.Observe(3.2,.20)&&t.Value==9.94,"小数大跳变拒绝");check(!t.Observe(9.5,2)&&t.Observe(9.45,2.05),"长时间中断重新两帧确认");
 check(GameClockWorker.ValidRegion(new RectangleF(.4f,.06f,.2f,.16f))&&!GameClockWorker.ValidRegion(new RectangleF(float.NaN,0,.2f,.1f))&&!GameClockWorker.ValidRegion(new RectangleF(.9f,0,.2f,.1f)),"手动区域边界检查");
 using(GameClockWorker w=new GameClockWorker())using(Bitmap b=new Bitmap(a[2]))using(ClockPanel panel=new ClockPanel(w,b)){
  panel.StartPosition=FormStartPosition.Manual;panel.Location=new Point(-20000,-20000);panel.Show();Application.DoEvents();using(Bitmap shot=new Bitmap(panel.Width,panel.Height)){panel.DrawToBitmap(shot,new Rectangle(Point.Empty,shot.Size));shot.Save(Path.Combine(a[1],"时间校准预览.png"));}panel.ClientSize=new Size(800,600);Application.DoEvents();using(Bitmap shot=new Bitmap(panel.Width,panel.Height)){panel.DrawToBitmap(shot,new Rectangle(Point.Empty,shot.Size));shot.Save(Path.Combine(a[1],"时间校准最小尺寸.png"));}panel.Hide();w.Export(a[1]);check(File.Exists(Path.Combine(a[1],"游戏时间","状态.txt")),"诊断导出包含状态和连续读数");
  using(ClockReader reader=new ClockReader())using(Bitmap tight=b.Clone(new Rectangle(835,60,200,140),System.Drawing.Imaging.PixelFormat.Format32bppArgb))check(reader.Read(tight)==49,"49 手动缩小截取区域仍识别");
  using(Bitmap shifted=new Bitmap(b.Width,b.Height+300)){using(Graphics g=Graphics.FromImage(shifted)){g.Clear(Color.Black);g.DrawImageUnscaled(b,0,300);}using(ClockReader reader=new ClockReader())using(Bitmap old=shifted.Clone(ClockReader.Area(shifted.Size),System.Drawing.Imaging.PixelFormat.Format32bppArgb))using(Bitmap corrected=shifted.Clone(new Rectangle(835,360,200,140),System.Drawing.Imaging.PixelFormat.Format32bppArgb)){check(!reader.Read(old).HasValue&&reader.Read(corrected)==49,"模拟顶部黑边：默认区域失败，手动校准恢复49");}}
 }
 }catch(Exception e){failures++;rows.Add(e.ToString());}rows.Add("FAILURES="+failures);File.WriteAllLines(Path.Combine(a[1],"时间55验证.txt"),rows);Environment.ExitCode=failures==0?0:1;}
}}
