using System;using System.Drawing;using System.Drawing.Drawing2D;using System.Windows.Forms;using System.IO;
namespace MuMuBeans {
sealed class ClockCanvas:Control {
 readonly Bitmap image;public RectangleF Selection;PointF start;bool dragging;public event Action<RectangleF> Selected;
 public ClockCanvas(Bitmap b){image=b==null?null:(Bitmap)b.Clone();DoubleBuffered=true;BackColor=Color.FromArgb(225,233,245);Cursor=Cursors.Cross;}
 RectangleF Fit(){if(image==null)return RectangleF.Empty;float s=Math.Min(Width/(float)image.Width,Height/(float)image.Height);return new RectangleF((Width-image.Width*s)/2,(Height-image.Height*s)/2,image.Width*s,image.Height*s);}
 PointF Norm(Point p){RectangleF r=Fit();return new PointF(Math.Max(0,Math.Min(1,(p.X-r.X)/r.Width)),Math.Max(0,Math.Min(1,(p.Y-r.Y)/r.Height)));}
 protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(image==null||e.Button!=MouseButtons.Left||!Fit().Contains(e.Location))return;start=Norm(e.Location);dragging=true;Capture=true;}
 protected override void OnMouseMove(MouseEventArgs e){base.OnMouseMove(e);if(!dragging)return;PointF n=Norm(e.Location);Selection=RectangleF.FromLTRB(Math.Min(n.X,start.X),Math.Min(n.Y,start.Y),Math.Max(n.X,start.X),Math.Max(n.Y,start.Y));Invalidate();}
 protected override void OnMouseUp(MouseEventArgs e){base.OnMouseUp(e);if(!dragging)return;dragging=false;Capture=false;if(Selected!=null)Selected(Selection);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);if(image==null){TextRenderer.DrawText(e.Graphics,"请先关闭此窗口，在主界面点击「扫描画面」\n再打开时间校准",Font,ClientRectangle,Color.DarkSlateGray,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);return;}RectangleF r=Fit();e.Graphics.DrawImage(image,r);RectangleF b=new RectangleF(r.X+Selection.X*r.Width,r.Y+Selection.Y*r.Height,Selection.Width*r.Width,Selection.Height*r.Height);using(Pen p=new Pen(Theme.Cyan,2))e.Graphics.DrawRectangle(p,b.X,b.Y,b.Width,b.Height);}
 protected override void Dispose(bool d){if(d&&image!=null)image.Dispose();base.Dispose(d);}
}
sealed class ClockPanel:Form {
 readonly GameClockWorker worker;readonly ClockCanvas canvas;readonly PictureBox crop=new PictureBox{SizeMode=PictureBoxSizeMode.Zoom,BackColor=Color.FromArgb(230,237,247)};readonly Label state=new Label(),hint=new Label();readonly Timer tick=new Timer{Interval=150};readonly CheckBox top=new CheckBox{Text="置顶观察",AutoSize=true};
 public ClockPanel(GameClockWorker w,Bitmap frame){worker=w;Text="游戏时间 · 校准与诊断";Font=new Font("Microsoft YaHei UI",10);BackColor=Theme.Bg;ClientSize=new Size(920,650);MinimumSize=new Size(800,600);StartPosition=FormStartPosition.CenterParent;
 canvas=new ClockCanvas(frame){Selection=w.State().Region};canvas.Selected+=delegate(RectangleF r){try{worker.SetRegion(r);hint.Text="已保存区域。WGC 可隔窗读取；若回退兼容截图，请移开遮挡。";}catch(Exception e){hint.Text=e.Message;canvas.Selection=worker.State().Region;canvas.Invalidate();}};
 hint.Text="在下方扫描预览中框选中间时间数字，留少量边距，不要包含上方“第几回”。";
 GlassButton reset=new GlassButton{Text="恢复默认区域",Icon="reset"},save=new GlassButton{Text="保存时间诊断",Icon="save"},done=new GlassButton{Text="完成",Primary=true};reset.Click+=delegate{try{worker.SetRegion(new RectangleF(.40f,.055f,.20f,.16f));canvas.Selection=worker.State().Region;canvas.Invalidate();}catch(Exception e){hint.Text=e.Message;}};save.Click+=delegate{try{string path=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"时间诊断_"+DateTime.Now.ToString("yyyyMMdd_HHmmss_fff"));worker.Export(path);hint.Text="已保存："+path;}catch(Exception e){hint.Text="保存失败："+e.Message;}};done.Click+=delegate{Close();};top.CheckedChanged+=delegate{TopMost=top.Checked;};
 Controls.AddRange(new Control[]{hint,canvas,crop,state,reset,save,done,top});Action layout=delegate{int width=ClientSize.Width,height=ClientSize.Height;hint.SetBounds(20,12,width-40,48);canvas.SetBounds(20,64,width-40,height-290);crop.SetBounds(20,height-208,230,110);state.SetBounds(270,height-210,width-290,130);reset.SetBounds(20,height-66,165,44);save.SetBounds(197,height-66,165,44);top.Location=new Point(380,height-54);done.SetBounds(width-120,height-66,100,44);};Resize+=delegate{layout();};layout();tick.Tick+=delegate{RefreshState();};tick.Start();RefreshState();}
 void RefreshState(){ClockState s=worker.State();Image old=crop.Image;crop.Image=worker.Preview();if(old!=null)old.Dispose();state.Text="最近截取区域（取帧失败时保留上一张）\r\n"+s.Status+"\r\n原始："+(s.Raw.HasValue?s.Raw.Value.ToString("0.00"):"—")+"    确认："+(s.Value.HasValue&&s.Age<=.6?s.Value.Value.ToString("0.00"):"—")+"    帧耗时："+s.ProcessMs.ToString("0")+"ms\r\n"+s.Backend+" · "+s.Method+"\r\n本帧匹配分数："+s.Confidence.ToString("0.00")+"（不是实战准确率）";}
 internal void SavePreview(string folder){StartPosition=FormStartPosition.Manual;Location=new Point(-20000,-20000);Show();Application.DoEvents();RefreshState();Refresh();using(Bitmap image=new Bitmap(Width,Height)){DrawToBitmap(image,new Rectangle(Point.Empty,Size));image.Save(Path.Combine(folder,"时间校准.png"));}ClientSize=new Size(800,600);Application.DoEvents();Refresh();using(Bitmap image=new Bitmap(Width,Height)){DrawToBitmap(image,new Rectangle(Point.Empty,Size));image.Save(Path.Combine(folder,"时间校准_最小.png"));}Hide();}
 protected override void Dispose(bool d){if(d){tick.Stop();tick.Dispose();if(crop.Image!=null)crop.Image.Dispose();}base.Dispose(d);}
}
}
